In [2]:
import pandas as pd
import numpy as np

dataset = pd.read_csv("D:\customer_shopping_behavior.csv")

In [3]:
dataset.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [10]:
dataset.describe(include = 'all') #describes the dataset

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [12]:
dataset.isnull().sum() #checks for null values

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
dataset['Review Rating'] = dataset.groupby('Category')['Review Rating'] . transform (lambda x : x.fillna(x.median()))

In [15]:
dataset.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [23]:
dataset.columns = dataset.columns.str.lower()
dataset.columns = dataset.columns.str.replace(' ','_')
dataset = dataset.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})

In [24]:
dataset.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount           0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [25]:
#creating a new age group:
labels = ['young adult' , 'Adult' , 'Middle Age' , 'Senior']

dataset['age_group'] = pd.qcut(dataset['age'] , q=4 , labels = labels)

In [29]:
dataset[['age' , 'age_group']].head(20)

    age    age_group
0    55   Middle Age
1    19  young adult
2    50   Middle Age
3    21  young adult
4    45   Middle Age
5    46   Middle Age
6    63       Senior
7    27  young adult
8    26  young adult
9    57   Middle Age
10   53   Middle Age
11   30  young adult
12   61       Senior
13   65       Senior
14   64       Senior
15   64       Senior
16   25  young adult
17   53   Middle Age
18   52   Middle Age
19   66       Senior

In [32]:
#frequency mapping

frequency_mapping = {
    
'Fortnightly': 14,
'Weekly' : 7,
'Monthly' : 30,
'Quarterly' : 90,
'Bi-Weekly' : 14,
'Annually' : 365,
'Every 3 Months' : 90
}

dataset['purchase_frequency_days'] = dataset['frequency_of_purchases'].map(frequency_mapping)

In [34]:
dataset[['purchase_frequency_days' , 'frequency_of_purchases']].head(20)

    purchase_frequency_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly
10                       14              Bi-Weekly
11                       14            Fortnightly
12                       14            Fortnightly
13                        7                 Weekly
14                        7                 Weekly
15                       30                Monthly
16                       14              Bi-Weekly
17                       90              Quarterly
18                        7                 Weekly
19                       14              Bi-Weekly

In [36]:
#checking if promo_codes and discount_used are similar

dataset[['promo_code_used' , 'discount_applied']].head(20)

   promo_code_used discount_applied
0              Yes              Yes
1              Yes              Yes
2              Yes              Yes
3              Yes              Yes
4              Yes              Yes
5              Yes              Yes
6              Yes              Yes
7              Yes              Yes
8              Yes              Yes
9              Yes              Yes
10             Yes              Yes
11             Yes              Yes
12             Yes              Yes
13             Yes              Yes
14             Yes              Yes
15             Yes              Yes
16             Yes              Yes
17             Yes              Yes
18             Yes              Yes
19             Yes              Yes

In [40]:
(dataset['promo_code_used'] == dataset['discount_applied']).all()

True

In [41]:
#no use in having the same table again
dataset = dataset.drop('promo_code_used' , axis = 1)

In [42]:
dataset.head(20)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle Age,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,young adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle Age,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,young adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle Age,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle Age,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,young adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,young adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle Age,90
10,11,53,Male,Shoes,Footwear,34,Arkansas,L,Purple,Fall,4.1,Yes,Store Pickup,Yes,26,Bank Transfer,Bi-Weekly,Middle Age,14
11,12,30,Male,Shorts,Clothing,68,Hawaii,S,Olive,Winter,4.9,Yes,Store Pickup,Yes,10,Bank Transfer,Fortnightly,young adult,14
12,13,61,Male,Coat,Outerwear,72,Delaware,M,Gold,Winter,4.5,Yes,Express,Yes,37,Venmo,Fortnightly,Senior,14
13,14,65,Male,Dress,Clothing,51,New Hampshire,M,Violet,Spring,4.7,Yes,Express,Yes,31,PayPal,Weekly,Senior,7
14,15,64,Male,Coat,Outerwear,53,New York,L,Teal,Winter,4.7,Yes,Free Shipping,Yes,34,Debit Card,Weekly,Senior,7
15,16,64,Male,Skirt,Clothing,81,Rhode Island,M,Teal,Winter,2.8,Yes,Store Pickup,Yes,8,PayPal,Monthly,Senior,30
16,17,25,Male,Sunglasses,Accessories,36,Alabama,S,Gray,Spring,4.1,Yes,Next Day Air,Yes,44,Debit Card,Bi-Weekly,young adult,14
17,18,53,Male,Dress,Clothing,38,Mississippi,XL,Lavender,Winter,4.7,Yes,2-Day Shipping,Yes,36,Venmo,Quarterly,Middle Age,90
18,19,52,Male,Sweater,Clothing,48,Montana,S,Black,Summer,4.6,Yes,Free Shipping,Yes,17,Cash,Weekly,Middle Age,7
19,20,66,Male,Pants,Clothing,90,Rhode Island,M,Green,Summer,3.3,Yes,Standard,Yes,46,Debit Card,Bi-Weekly,Senior,14

In [44]:
!pip install mysql-connector-python pandas sqlalchemy ipython-sql pymysql

Requirement already satisfied: mysql-connector-python in c:\users\nithi\anaconda3\lib\site-packages (9.4.0)
Requirement already satisfied: pandas in c:\users\nithi\anaconda3\lib\site-packages (1.4.4)
Requirement already satisfied: sqlalchemy in c:\users\nithi\anaconda3\lib\site-packages (2.0.44)
Requirement already satisfied: ipython-sql in c:\users\nithi\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: pymysql in c:\users\nithi\anaconda3\lib\site-packages (1.1.3)
Requirement already satisfied: numpy>=1.18.5 in c:\users\nithi\anaconda3\lib\site-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\nithi\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\nithi\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nithi\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet>=1 in c:\users\nithi\anaconda3\lib\site-packages (from sqlalchemy) (1.1.1)
Requirement already satisfied: sqlparse in c:\users\nithi\anaconda3\lib\site-packages (from ipython-sql) (0.5.4)
Requirement already satisfied: ipython-genutils in c:\users\nithi\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: prettytable in c:\users\nithi\anaconda3\lib\site-packages (from ipython-sql) (3.16.0)
Requirement already satisfied: ipython in c:\users\nithi\anaconda3\lib\site-packages (from ipython-sql) (8.2.0)
Requirement already satisfied: six in c:\users\nithi\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: pygments>=2.4.0 in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.11.2)
Requirement already satisfied: colorama in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.4)
Requirement already satisfied: traitlets>=5 in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.20)
Requirement already satisfied: pickleshare in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.7.5)
Requirement already satisfied: jedi>=0.16 in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: backcall in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (61.2.0)
Requirement already satisfied: decorator in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: stack-data in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: matplotlib-inline in c:\users\nithi\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\nithi\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: wcwidth in c:\users\nithi\anaconda3\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->ipython-sql) (0.2.5)
Requirement already satisfied: asttokens in c:\users\nithi\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: executing in c:\users\nithi\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: pure-eval in c:\users\nithi\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

In [53]:
import mysql.connector
import pandas as pd

from sqlalchemy import create_engine, text

# MySQL credentials
username = "root"
password = "root"
host = "127.0.0.1"
port = "3306"
database = "customer_behavior"

print("Connected successfully!")

# Create engine
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

# Upload dataframe to MySQL
table_name = "customer"

dataset.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

# Read data back
with engine.connect() as conn:

    query = text("SELECT * FROM customer LIMIT 5;")

    result = pd.read_sql(
        query,
        conn
    )

print(result)

Connected successfully!
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly   Middle Age                       14
1            Fortnightly  young adult                       14
2                 Weekly   Middle Age                        7
3                 Weekly  young adult                        7
4               Annually   Middle Age                      365

In [58]:
with engine.connect() as conn:

    query = text("SELECT location from customer ;")

    result = pd.read_sql(
        query,
        conn
    )

print(result)

           location
0          Kentucky
1             Maine
2     Massachusetts
3      Rhode Island
4            Oregon
...             ...
3895       Virginia
3896           Iowa
3897     New Jersey
3898      Minnesota
3899     California

[3900 rows x 1 columns]

In [60]:
--Q1. What is the total revenue generated by male vs. female customers?



with engine.connect() as conn:

    query = text("select gender , sum(purchase_amount) as revenue from customer group by gender;")

    result = pd.read_sql(
        query,
        conn
    )

print(result)

Object `customers` not found.
   gender   revenue
0    Male  157890.0
1  Female   75191.0